### PR TITLE
Scratchpad stop un and re subscribing

### PR DESCRIPTION
**Pull request by Kasper24**
This makes things easier and cleaner to understand. It also fixes a new issues that arose from a new rubato change

### CODE REVIEW

**Comment by Kasper24** [comment]
@JavaCafe01 @Nooo37 Can you guys test this is working for you under the lastest rubato commit?

**Comment by JavaCafe01** [comment]
@Kasper24 This does not work for me. I'm on the latest commit for Rubato.

Here's my scratchpad config:
```lua
local chat_anim = {
    y = rubato.timed {
        pos = 1090,
        rate = 120,
        easing = rubato.quadratic,
        intro = 0.1,
        duration = 0.3,
        awestore_compat = true
    }
}

local chat_scratch = bling.module.scratchpad:new{
    -- command = [[ firefox -P chat --new-tab -url https://discord.com/channels/@me --class chat ]],
    command = "Discord",
    rule = {
        -- class = "chat"
        class = "discord"
    },
    sticky = false,
    autoclose = false,
    floating = true,
    geometry = {x = dpi(460), y = dpi(90), height = dpi(900), width = dpi(1000)},
    reapply = true,
    rubato = chat_anim
}

awesome.connect_signal("scratch::chat", function() chat_scratch:toggle() end)
```

The scratchpad spawns Discord, but after it animates and hides, it will not show up again.

**Review by JavaCafe01 — APPROVED** [review]

**Comment by JavaCafe01** [comment]
@Nooo37 ?

**Review by Nooo37 — APPROVED** [review]
Works fine with the latest rubato :thumbsup:

**Pull request merged**
