### PR TITLE
Old playerctl cli backend added as option

### PR DESCRIPTION
**Pull request by HumblePresent**
This PR makes the old cli-based backend for the playerctl module available as an option configured through a `beautiful` theme variable for users on distros whose playerctl packages do not support use of the playerctl library through lgi bindings.

- [x] code
- [x] docs

### CODE REVIEW

**Comment by HumblePresent** [comment]
If this looks ok I'll go ahead and update the docs as well.

**Comment by HumblePresent** [comment]
Actually I just saw #49 and I'll try to address that in this PR as well.

**Comment by JavaCafe01** [comment]
Op means #48

**Comment by undefinedDarkness** [comment]
Pog, thanks for the option

**Comment by JavaCafe01** [comment]
@HumblePresent I'm thinking the old backend should be an arg option, not a theme variable

**Comment by HumblePresent** [comment]
Yeah I also had that thought. I think it should be both because every other config parameter is both an `enable()` paramter and theme variable so it makes sense that this should be too. I also think the parameter name should be something more descriptive than `old_backend` because new users aren't really going to understand what that means. I called it `playerctl_cli` but that isn't great either because there isn't really any CLI involved. I'll think on that and lmk what you think.

**Comment by Nooo37** [comment]
Doing it both ways - theme vars and function arguments - is probably rather confusing. We haven't had that case yet afaik and it's probably better to only have one option to customize. So far there haven't been any parameters to `enable` functions at all but I think it would be fitting in that case.

**Comment by Killua7362** [comment]
it worked on nixos! thank you @HumblePresent!

**Comment by HumblePresent** [comment]
@Nooo37 I suggested both because the `enable()` function for the playerctl module now takes arguments for configuration  that will override the configuration via theme variables as of my last PR. Basically, it can be configured with parameters passed directly to the enable function or with theme variables. I'm fine with just adding the backend option as an `enable()` parameter though if that's what you think is best.

**Comment by Nooo37** [comment]
@HumblePresent Oh yea you are right. That priorization of direct arguments over theme vars makes sense as it is analogous to what awesomewm built-in widgets do. Do it the way you wanted to :+1:

**Comment by JavaCafe01** [comment]
> I also think the parameter name should be something more descriptive than old_backend because new users aren't really going to understand what that means.

@HumblePresent  I think that old_backend should be enough, as we should explain what it means in the docs - and new users should be reading the docs :smile:

**Comment by undefinedDarkness** [comment]
Or since the problem with the current system only seems to be the require statement maybe we could have a protected call or only require it when it is enabled

**Comment by HumblePresent** [comment]
@JavaCafe01 that sounds good. I have made some changes to add the backend as a parameter to the `enable()` function but I need to test it before I push. Hopefully that will be tonight. I agree the CLI backend could be made default. They will need to be explained in the docs anyway.

**Comment by HumblePresent** [comment]
Alright I've pushed by code changes. Haven't done the docs yet as that is a little more complicated given that the CLI backend doesn't support all the config parameters or any config parameters as arguments passed directly to `enable()`.

**Review by JavaCafe01 — APPROVED** [review]

**Pull request merged**
