### PR TITLE
Draft: Fix scratchpad rules not being applied when an existing client is not found

### PR DESCRIPTION
**Pull request by Kasper24**
I can't be sure, but I think the issue is that if you have any matching rule for that client it will overwrite what the scratchpad is setting. 

Update:
Marked it as draft for now, I'm testing further changes for this

### CODE REVIEW

**Comment by JavaCafe01** [comment]
@Nooo37

**Comment by Nooo37** [comment]
I mean ideally one wouldn't have conflicting rules and scratchpad matches but sure that seems like a valid improvement. What further changes are you testing?

**Comment by Kasper24** [comment]
> I mean ideally one wouldn't have conflicting rules and scratchpad matches but sure that seems like a valid improvement. What further changes are you testing?

I use scratchpads mainly while I'm gaming, so I'll have a rule for Discord where it will spawn normally on tag 5 and switch to that tag and that can be a problem.

I encountered a lot of edge cases even with the last fix, so I tried making some changes at 40e0ac5cdc65ccc92900504c1e1b0babafcfa051. I left some comments there to make sense of what I did. I tried different methods of applying these rules, and this seem to be the one that has the least amount of issues.

**Comment by Nooo37** [comment]
I fear the usage of `ruled` would break 4.3 compatibility :pensive:

**Comment by Kasper24** [comment]
@Nooo37 Right, didn't think about it. Maybe we can only use that if API version is greater than 4.3?

**Comment by Nooo37** [comment]
We theoretically could do a big `if awesome.version ~= "v4.4"` block (and I actually did something similar for the wallpaper module #70) but I wouldn't be big of a fan of it in that case. In the wallpaper module it was just a check and one command per version (as there isn't a request::wallpaper signal in 4.3 but it's way more flexible to use signals).  In this case we would have to create a very big block (including the require statement) which wouldn't be clean I think. It also would cause different behaviors for the versions. 

I don't really understand what you are doing with your discord window but it might be easier to fix that user-side with the newly-merged scratchpad signals. Maybe have a look into that? Would also be interesting to see if they can endure a field-test in their current form.

**Comment by Kasper24** [comment]
> We theoretically could do a big `if awesome.version ~= "v4.4"` block (and I actually did something similar for the wallpaper module #70) but I wouldn't be big of a fan of it in that case. In the wallpaper module it was just a check and one command per version (as there isn't a request::wallpaper signal in 4.3 but it's way more flexible to use signals). In this case we would have to create a very big block (including the require statement) which wouldn't be clean I think. It also would cause different behaviors for the versions.

Well, not sure what would be a better solution then... with the code in the master branch none of the rules apply if the app isn't already running, regardless if you have any overlapping rules or not. 

> I don't really understand what you are doing with your discord window but it might be easier to fix that user-side with the newly-merged scratchpad signals. Maybe have a look into that? Would also be interesting to see if they can endure a field-test in their current form.

When you launch Discord it opens up 2 windows, 1 after the other - first one is the "Discord Updater" and once that's done it opens up the actual Discord window (quite common among electron apps to do this). This is quite specific to some apps, but I thought it might be worth including as Discord should be a common app to use a scratchpad, and I saw some other example in code where you added specific code to handle misbehaving apps so I thought it would make sense.

**Comment by Nooo37** [comment]
> The issue is that with the code in the master branch none of the rules apply if the app isn't already running, regardless if you have any overlapping rules or not.

Just to clarify: You are talking about discord / other electron apps specifically here right?

> When you launch Discord it opens up 2 windows, 1 after the other - first one is the "Discord Updater" and once that's done it opens up the actual Discord window (quite common among electron apps to do this)

Hmm, right. I have `reapply` set to true on discord (that's probably why I set it that way) so I didn't really notice it myself. What if we don't unconnect the `inital_apply` at all? That way it shouldn't have a false positive on the first discord updater window, should it? 

Generally finding the client that corresponds to the spawn command is a sisyphean task. The PID approach is in general very weak and error-prone I think. I'm wondering rn why I didn't just check if the given rule is matching any of the newly spawned clients. In retrospect it seems dumb to check if the PIDs are "matching up" instead of just checking if the rule matches which is what the rule is there for :sweat_smile:. So essentially we could connect the `manage` signal to a function that checks if the rules is matching and if so, it applies the properties (without disconnecting, the connection itself would happen in the `::new` function). Any thoughts on that?

**Comment by Kasper24** [comment]
> Just to clarify: You are talking about discord / other electron apps specifically here right?
No, the part below is about discord / other electron apps

> Generally finding the client that corresponds to the spawn command is a sisyphean task. The PID approach is in general very weak and error-prone I think. I'm wondering rn why I didn't just check if the given rule is matching any of the newly spawned clients. 

Yeah, I was first making use of the rule property, but I wasn't sure if it was required to be configured so just left it as is for the PR.


> In retrospect it seems dumb to check if the PIDs are "matching up" instead of just checking if the rule matches which is what the rule is there for sweat_smile. So essentially we could connect the manage signal to a function that checks if the rules is matching and if so, it applies the properties (without disconnecting, the connection itself would happen in the ::new function). Any thoughts on that?

The issue with using the ::manage signal, is in the case someone might want to set some properties for the client before the delayed_call he can't do it. If using ruled, he can set all the properties apart from geometry ones and they will apply. 
For example, you can't do switch_to_tag = false as when the scratchpad properties are applied it's already after the tag was switched (in-case there is a matching rule with switch_to_tag = true that is)

**Comment by Nooo37** [comment]
> Yeah, I was first making use of the rule property, but I wasn't sure if it was required to be configured so just left it as is for the PR.

It is required. Probably should make that more clear in the docs. Otherwise we have no way of telling which client the scratchpad is. So we might just as well use it to identify which spawned client correponds to the spawn command.

So my proposal would look like this (at the end of ::new):

```lua
awesome.connect_signal("manage", function(c)
    if awful.rules.match(c, ret.rule) then
        ret:apply(c)
    end
end)
```

and then we would have to get rid of the whole "inital_apply" part .

One could still set arbitrary rules for the same client (rules get applied before the `manage` signal fires right? If not, we could put a `delayed_call` in there). So what is hindering users to set `switch_to_tag` to false in their own rules? That's what I'm not understanding.

**Comment by Nooo37** [comment]
@Kasper24 Can you maybe try whether the changes I've tried here are fixing your problems: https://github.com/BlingCorp/bling/commit/0cb907c746a701a824429078f57d04f523f0681b

**Comment by Kasper24** [comment]
> @Kasper24 Can you maybe try whether the changes I've tried here are fixing your problems: [0cb907c](https://github.com/BlingCorp/bling/commit/0cb907c746a701a824429078f57d04f523f0681b)

None of the rules were applied from my testing.

Would it not be possible to insert a rule onto the table for the stable version?

**Comment by Nooo37** [comment]
@Kasper24 I'm not really a fan of adding rules into there to be honest because 
1. The 4.3 and 4.4 rule functions are very different (two "branches" in the code for which we will have to take care and keep in sync in terms of features)
2. Manually inserting rules (without the user knowing) might lead to more problems for the user 
3. We should be able to recreate the rule behavior by connecting to the `manage` signal: awesomewm rules are not much more than that.

**Comment by Nooo37** [comment]
The PR does solve the problem you described. Thanks for your work and sorry for taking so long :sweat_smile:

**Pull request merged**
